ARG NEXTCLOUD_TAG=34
FROM nextcloud:${NEXTCLOUD_TAG}-fpm

RUN set -ex; \
    \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        ffmpeg \
        ghostscript \
    ; \
    rm -rf /var/lib/apt/lists/*

COPY context/scripts/configure.sh /configure.sh
COPY context/scripts/notify_push.sh /notify_push.sh
COPY context/scripts/previewgenerator.sh /previewgenerator.sh
COPY context/scripts/recognize-worker.sh /recognize-worker.sh
RUN chmod +x /configure.sh /notify_push.sh /previewgenerator.sh /recognize-worker.sh
COPY context/configs/prev.config.php /usr/src/nextcloud/config/
COPY context/configs/phone.config.php /usr/src/nextcloud/config/
COPY context/configs/log.config.php /usr/src/nextcloud/config/
COPY context/configs/zz-log.conf /usr/local/etc/php-fpm.d/
ENTRYPOINT ["/configure.sh"]
CMD /entrypoint.sh php-fpm
