---
- name: Reload nextcloud quadlets
  ansible.builtin.command: systemctl --user -M nextcloud@ daemon-reload  # noqa: command-instead-of-module
  changed_when: true
  listen: nextcloud quadlets changed

- name: Restart nextcloud pod
  ansible.builtin.command: systemctl --user -M nextcloud@ restart nc-pod.service  # noqa: command-instead-of-module
  changed_when: true
  listen: nextcloud quadlets changed
